version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: standard
  enable:
    - errcheck
    - errorlint
    - exhaustive
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocritic
    - govet
    - ineffassign
    - misspell
    - nilerr
    - noctx
    - revive
    - staticcheck
    - unused
  settings:
    revive:
      severity: warning
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: exported
        - name: if-return
        - name: indent-error-flow
        - name: increment-decrement
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: superfluous-else
        - name: time-naming
        - name: var-naming
        - name: waitgroup-by-value
formatters:
  enable:
    - gofmt
    - goimports
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
